#############################################################################
# Makefile for building: bin/scdParser
# Generated by qmake (3.1) (Qt 5.12.1)
# Project:  scdParser.pro
# Template: app
# Command: /usr/local/Qt5.12.1/bin/qmake -o Makefile scdParser.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -D_LINUX_ -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/local/Qt5.12.1/include -I/usr/local/Qt5.12.1/include/QtGui -I/usr/local/Qt5.12.1/include/QtCore -ILinuxTmp -I/usr/local/Qt5.12.1/mkspecs/linux-g++
QMAKE         = /usr/local/Qt5.12.1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/Qt5.12.1/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/Qt5.12.1/bin/qmake -install qinstall -exe
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = scdParser1.0.0
DISTDIR = /home/scdParse/scdParser/LinuxTmp/scdParser1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Qt5.12.1/lib
LIBS          = $(SUBLIBS) -lsqlite3 -L/usr/local/Qt5.12.1/lib -lQt5Gui -lQt5Core -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = LinuxTmp/

####### Files

SOURCES       = genlists.c \
		sclparse.c \
		sclPub.c \
		sclstore.c \
		slog.c \
		storage.c \
		str_util.c \
		sx_dec.c \
		sx_enc.c \
		testScdPaser.c \
		time_str.c 
OBJECTS       = LinuxTmp/genlists.o \
		LinuxTmp/sclparse.o \
		LinuxTmp/sclPub.o \
		LinuxTmp/sclstore.o \
		LinuxTmp/slog.o \
		LinuxTmp/storage.o \
		LinuxTmp/str_util.o \
		LinuxTmp/sx_dec.o \
		LinuxTmp/sx_enc.o \
		LinuxTmp/testScdPaser.o \
		LinuxTmp/time_str.o
DIST          = /usr/local/Qt5.12.1/mkspecs/features/spec_pre.prf \
		/usr/local/Qt5.12.1/mkspecs/common/unix.conf \
		/usr/local/Qt5.12.1/mkspecs/common/linux.conf \
		/usr/local/Qt5.12.1/mkspecs/common/sanitize.conf \
		/usr/local/Qt5.12.1/mkspecs/common/gcc-base.conf \
		/usr/local/Qt5.12.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt5.12.1/mkspecs/common/g++-base.conf \
		/usr/local/Qt5.12.1/mkspecs/common/g++-unix.conf \
		/usr/local/Qt5.12.1/mkspecs/qconfig.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt5.12.1/mkspecs/features/qt_functions.prf \
		/usr/local/Qt5.12.1/mkspecs/features/qt_config.prf \
		/usr/local/Qt5.12.1/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt5.12.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt5.12.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt5.12.1/mkspecs/features/toolchain.prf \
		/usr/local/Qt5.12.1/mkspecs/features/default_pre.prf \
		/usr/local/Qt5.12.1/mkspecs/features/resolve_config.prf \
		/usr/local/Qt5.12.1/mkspecs/features/default_post.prf \
		/usr/local/Qt5.12.1/mkspecs/features/warn_on.prf \
		/usr/local/Qt5.12.1/mkspecs/features/qt.prf \
		/usr/local/Qt5.12.1/mkspecs/features/resources.prf \
		/usr/local/Qt5.12.1/mkspecs/features/moc.prf \
		/usr/local/Qt5.12.1/mkspecs/features/unix/thread.prf \
		/usr/local/Qt5.12.1/mkspecs/features/qmake_use.prf \
		/usr/local/Qt5.12.1/mkspecs/features/file_copies.prf \
		/usr/local/Qt5.12.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt5.12.1/mkspecs/features/exceptions.prf \
		/usr/local/Qt5.12.1/mkspecs/features/yacc.prf \
		/usr/local/Qt5.12.1/mkspecs/features/lex.prf \
		scdParser.pro gen_list.h \
		glbtypes.h \
		mem_chk.h \
		scdParse_export.h \
		scl.h \
		sclPub.h \
		slog.h \
		storage.h \
		str_util.h \
		sx_arb.h \
		sx_defs.h \
		sysincs.h \
		time_str.h genlists.c \
		sclparse.c \
		sclPub.c \
		sclstore.c \
		slog.c \
		storage.c \
		str_util.c \
		sx_dec.c \
		sx_enc.c \
		testScdPaser.c \
		time_str.c
QMAKE_TARGET  = scdParser
DESTDIR       = bin/
TARGET        = bin/scdParser


first: all
####### Build rules

bin/scdParser:  $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: scdParser.pro /usr/local/Qt5.12.1/mkspecs/linux-g++/qmake.conf /usr/local/Qt5.12.1/mkspecs/features/spec_pre.prf \
		/usr/local/Qt5.12.1/mkspecs/common/unix.conf \
		/usr/local/Qt5.12.1/mkspecs/common/linux.conf \
		/usr/local/Qt5.12.1/mkspecs/common/sanitize.conf \
		/usr/local/Qt5.12.1/mkspecs/common/gcc-base.conf \
		/usr/local/Qt5.12.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt5.12.1/mkspecs/common/g++-base.conf \
		/usr/local/Qt5.12.1/mkspecs/common/g++-unix.conf \
		/usr/local/Qt5.12.1/mkspecs/qconfig.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt5.12.1/mkspecs/features/qt_functions.prf \
		/usr/local/Qt5.12.1/mkspecs/features/qt_config.prf \
		/usr/local/Qt5.12.1/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt5.12.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt5.12.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt5.12.1/mkspecs/features/toolchain.prf \
		/usr/local/Qt5.12.1/mkspecs/features/default_pre.prf \
		/usr/local/Qt5.12.1/mkspecs/features/resolve_config.prf \
		/usr/local/Qt5.12.1/mkspecs/features/default_post.prf \
		/usr/local/Qt5.12.1/mkspecs/features/warn_on.prf \
		/usr/local/Qt5.12.1/mkspecs/features/qt.prf \
		/usr/local/Qt5.12.1/mkspecs/features/resources.prf \
		/usr/local/Qt5.12.1/mkspecs/features/moc.prf \
		/usr/local/Qt5.12.1/mkspecs/features/unix/thread.prf \
		/usr/local/Qt5.12.1/mkspecs/features/qmake_use.prf \
		/usr/local/Qt5.12.1/mkspecs/features/file_copies.prf \
		/usr/local/Qt5.12.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt5.12.1/mkspecs/features/exceptions.prf \
		/usr/local/Qt5.12.1/mkspecs/features/yacc.prf \
		/usr/local/Qt5.12.1/mkspecs/features/lex.prf \
		scdParser.pro \
		/usr/local/Qt5.12.1/lib/libQt5Gui.prl \
		/usr/local/Qt5.12.1/lib/libQt5Core.prl
	$(QMAKE) -o Makefile scdParser.pro
/usr/local/Qt5.12.1/mkspecs/features/spec_pre.prf:
/usr/local/Qt5.12.1/mkspecs/common/unix.conf:
/usr/local/Qt5.12.1/mkspecs/common/linux.conf:
/usr/local/Qt5.12.1/mkspecs/common/sanitize.conf:
/usr/local/Qt5.12.1/mkspecs/common/gcc-base.conf:
/usr/local/Qt5.12.1/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt5.12.1/mkspecs/common/g++-base.conf:
/usr/local/Qt5.12.1/mkspecs/common/g++-unix.conf:
/usr/local/Qt5.12.1/mkspecs/qconfig.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_mqtt.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_mqtt_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt5.12.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Qt5.12.1/mkspecs/features/qt_functions.prf:
/usr/local/Qt5.12.1/mkspecs/features/qt_config.prf:
/usr/local/Qt5.12.1/mkspecs/linux-g++/qmake.conf:
/usr/local/Qt5.12.1/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Qt5.12.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt5.12.1/mkspecs/features/toolchain.prf:
/usr/local/Qt5.12.1/mkspecs/features/default_pre.prf:
/usr/local/Qt5.12.1/mkspecs/features/resolve_config.prf:
/usr/local/Qt5.12.1/mkspecs/features/default_post.prf:
/usr/local/Qt5.12.1/mkspecs/features/warn_on.prf:
/usr/local/Qt5.12.1/mkspecs/features/qt.prf:
/usr/local/Qt5.12.1/mkspecs/features/resources.prf:
/usr/local/Qt5.12.1/mkspecs/features/moc.prf:
/usr/local/Qt5.12.1/mkspecs/features/unix/thread.prf:
/usr/local/Qt5.12.1/mkspecs/features/qmake_use.prf:
/usr/local/Qt5.12.1/mkspecs/features/file_copies.prf:
/usr/local/Qt5.12.1/mkspecs/features/testcase_targets.prf:
/usr/local/Qt5.12.1/mkspecs/features/exceptions.prf:
/usr/local/Qt5.12.1/mkspecs/features/yacc.prf:
/usr/local/Qt5.12.1/mkspecs/features/lex.prf:
scdParser.pro:
/usr/local/Qt5.12.1/lib/libQt5Gui.prl:
/usr/local/Qt5.12.1/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile scdParser.pro

qmake_all: FORCE


all: Makefile bin/scdParser

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Qt5.12.1/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents gen_list.h glbtypes.h mem_chk.h scdParse_export.h scl.h sclPub.h slog.h storage.h str_util.h sx_arb.h sx_defs.h sysincs.h time_str.h $(DISTDIR)/
	$(COPY_FILE) --parents genlists.c sclparse.c sclPub.c sclstore.c slog.c storage.c str_util.c sx_dec.c sx_enc.c testScdPaser.c time_str.c $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core
	-$(DEL_FILE) $(TARGET)

distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: LinuxTmp/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) LinuxTmp/moc_predefs.h
LinuxTmp/moc_predefs.h: /usr/local/Qt5.12.1/mkspecs/features/data/dummy.cpp
	g++ -pipe -D_LINUX_ -O2 -std=gnu++11 -Wall -W -dM -E -o LinuxTmp/moc_predefs.h /usr/local/Qt5.12.1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

LinuxTmp/genlists.o: genlists.c glbtypes.h \
		sysincs.h \
		gen_list.h \
		scdParse_export.h \
		slog.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LinuxTmp/genlists.o genlists.c

LinuxTmp/sclparse.o: sclparse.c glbtypes.h \
		sysincs.h \
		mem_chk.h \
		sx_defs.h \
		str_util.h \
		scl.h \
		gen_list.h \
		scdParse_export.h \
		slog.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LinuxTmp/sclparse.o sclparse.c

LinuxTmp/sclPub.o: sclPub.c sclPub.h \
		glbtypes.h \
		mem_chk.h \
		sysincs.h \
		slog.h \
		scdParse_export.h \
		gen_list.h \
		scl.h \
		str_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LinuxTmp/sclPub.o sclPub.c

LinuxTmp/sclstore.o: sclstore.c glbtypes.h \
		sysincs.h \
		scl.h \
		gen_list.h \
		scdParse_export.h \
		str_util.h \
		mem_chk.h \
		slog.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LinuxTmp/sclstore.o sclstore.c

LinuxTmp/slog.o: slog.c glbtypes.h \
		sysincs.h \
		slog.h \
		scdParse_export.h \
		gen_list.h \
		str_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LinuxTmp/slog.o slog.c

LinuxTmp/storage.o: storage.c storage.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LinuxTmp/storage.o storage.c

LinuxTmp/str_util.o: str_util.c glbtypes.h \
		sysincs.h \
		str_util.h \
		slog.h \
		scdParse_export.h \
		gen_list.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LinuxTmp/str_util.o str_util.c

LinuxTmp/sx_dec.o: sx_dec.c glbtypes.h \
		sysincs.h \
		mem_chk.h \
		scl.h \
		gen_list.h \
		scdParse_export.h \
		sx_defs.h \
		str_util.h \
		slog.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LinuxTmp/sx_dec.o sx_dec.c

LinuxTmp/sx_enc.o: sx_enc.c glbtypes.h \
		sysincs.h \
		mem_chk.h \
		time_str.h \
		sx_defs.h \
		slog.h \
		scdParse_export.h \
		gen_list.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LinuxTmp/sx_enc.o sx_enc.c

LinuxTmp/testScdPaser.o: testScdPaser.c sclPub.h \
		glbtypes.h \
		mem_chk.h \
		sysincs.h \
		slog.h \
		scdParse_export.h \
		gen_list.h \
		scl.h \
		storage.h \
		str_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LinuxTmp/testScdPaser.o testScdPaser.c

LinuxTmp/time_str.o: time_str.c glbtypes.h \
		sysincs.h \
		slog.h \
		scdParse_export.h \
		gen_list.h \
		time_str.h \
		sx_defs.h \
		str_util.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o LinuxTmp/time_str.o time_str.c

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

